### PR TITLE
Created DDL commands

### PR DESCRIPTION
**Pull request by leovaldez08**
Added all the tables and attributes in mysql.

Loom video link explaining DDL Commands: [Link](https://www.loom.com/share/9f88d469939448648a2c99df6ec45f8e?sid=68d1dd85-b553-452b-aabc-6b8fa6e12f1f)
Demo video link: [Link](https://www.loom.com/share/e909d74846bc4cec9902044ff5ed7c4a?sid=1993c7d4-b46d-4266-a093-ce730c8131bc)

### CODE REVIEW

**Comment by th3c0d3br34ker** [comment]
thanks @leovaldez08 for your submission. the self-viva covers `DDL commands` well.

however a demo is missing (you did not execute the commands shown). please consider re-submitting with the demo link.

thanks.

**Comment by leovaldez08** [comment]
Hey @th3c0d3br34ker, I've updated the link for the demo, Pls check it out and let me know. Also the previous PR is yet to be merged. So requesting you to look into it! Thanks in advance!

**Comment by th3c0d3br34ker** [comment]
hey @leovaldez08, please refrain from editing the comments. you may always add a new comment.

please re-submit on kalvium.community as well.

**Comment by leovaldez08** [comment]
Hey @th3c0d3br34ker, I've re-submitted the links again, it's evaluated with the note saying, left feedback on the PR, but there are no new feedback on the PR. What should I do now? please look into this and let me know If I can merge the pending PRs!

**Comment by th3c0d3br34ker** [comment]
yes, please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
